use soroban_sdk::contracterror;

#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum GovernorError {
    UnauthorizedCancel = 1,
    InvalidSupport = 2,
    ProposalExpired = 3,
    CalldataTooLarge = 4,
    InvalidCalldata = 5,
    ProposalRateLimited = 6,
    ContractPaused = 7,
    UnauthorizedPause = 8,
    InvalidVectorLengths = 9,
    NoTargets = 10,
    ProposalThresholdNotMet = 11,
    AlreadyVoted = 12,
    ZeroVotingPower = 13,
    ProposalNotSucceeded = 14,
    ProposalNotQueued = 15,
    ProposalAlreadyExecuted = 16,
    MissingOpIds = 17,
    UnauthorizedGuardian = 18,
    VetoWindowClosed = 19,
    ProposalNotFound = 20,
    TimelockNotSet = 21,
    GuardianNotSet = 22,
    TooManyTokens = 23,
    EmptyMetadataUri = 24,
    VotesTokenNotSet = 25,
    PauserNotSet = 26,
    ArithmeticOverflow = 27,
    VotePeriodTooShort = 28,
    ExecutionWindowZero = 29,
    TooManyCalldataEntries = 30,
    ProposalNotActive = 31,
    AlreadyInitialized = 32,
    InvalidVotingDelay = 33,
    InvalidVotingPeriod = 34,
    InvalidQuorumNumerator = 35,
    InvalidProposalThreshold = 36,
    InvalidMaxCalldataSize = 37,
    InvalidMaxProposalsPerPeriod = 38,
    InvalidProposalPeriodDuration = 39,
    EmptyBatch = 40,
    BatchProposalNotQueued = 41,
    ProposalAlreadyCancelled = 42,
    InvalidVoteChoice = 43,
    UnauthorizedRegistry = 44,
    // Soroban's #[contracterror] enum caps out at 50 cases (ScSpecUdtErrorEnumV0::cases
    // is a VecM<_, 50>), so these 6 are the only new variants Issue #766 gets — the
    // rest of its otherwise-listed error names (CommitmentNotFound, AlreadyCommitted,
    // CommitRevealRequired) are folded into the closest existing/new variant below
    // rather than exhausting the last of the budget.
    CommitPhaseEnded = 45,
    RevealPhaseNotStarted = 46,
    RevealPhaseEnded = 47,
    CommitmentMismatch = 48,
    NoCommitmentToReveal = 49,
    CommitRevealNotEnabled = 50,
}
